### ISSUE TITLE
Finish curating RIM for WebRAVE, ArcRAVE and QRAVE

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RIM#14]
Currently, RIM projects were curated by @kbartelt to work for ArcRAVE and are about 95% of way there (see fixes in Riverscapes/RIM#12 and Riverscapes/RIM#13).  We need to do same across whole suite. These are tracked over in: 

- [ ] https://github.com/Riverscapes/RiverscapesXML/issues/436

These are working, with some small curation and WebRAVE problems. Elaborating these issues:
- [ ] RIM projects incorrectly showing primary output of. Inundation Types as polylines instead of polygons (https://github.com/Riverscapes/RiverscapesXML/issues/485)
- [ ] RIM projects still have a number of tiling errors in webRAVE of rasters. @CHafen please go through and identify which projects have them and which layers. 
- [ ] RIM projects still not showing DEMs and Hillshades? (see https://github.com/Riverscapes/RiverscapesXML/issues/448)
- [ ] Riverscapes/RiverscapesXML#486
- [ ] Some dam status issues still (https://github.com/Riverscapes/RiverscapesXML/issues/451)

@CHafen please work on these with @jtgilbert or @MattReimer if you need help. Thanks! We are close to publishing this manuscript, so this is time sensitive.

**Comment by CHafen** [comment]
@jtgilbert could you send me a link to where these are in the warehouse?

**Comment by jtgilbert** [comment]
@CHafen 
https://data.riverscapes.xyz/#/USFS_PIBO

**Comment by joewheaton** [comment]
These are working, with some small curation and WebRAVE problems. Elaborating these issues:
- [ ] RIM projects incorrectly showing primary output of. Inundation Types as polylines instead of polygons
- [ ] RIM projects still have a number of tiling errors in webRAVE
- [ ] RIM projects still not showing DEMs and Hillshades?
- [ ] Resolution of

@CHafen please work on these with @jtgilbert or @MattReimer if you need help. Thanks! We are close to publishing this manuscript, so this is time sensitive.
